const keymap = [
  { y: 0, x: 0, key: "S1-" },
  { y: 0, x: 1, key: "T-" },
  { y: 0, x: 2, key: "P-" },
  { y: 0, x: 3, key: "H-" },
  { y: 0, x: 4, key: "*1" },
  { y: 0, x: 5, key: "*3" },
  { y: 0, x: 6, key: "-F" },
  { y: 0, x: 7, key: "-P" },
  { y: 0, x: 8, key: "-L" },
  { y: 0, x: 9, key: "-T" },
  { y: 0, x: 10, key: "-D" },

  { y: 1, x: 0, key: "S2-" },
  { y: 1, x: 1, key: "K-" },
  { y: 1, x: 2, key: "W-" },
  { y: 1, x: 3, key: "R-" },
  { y: 1, x: 4, key: "*2" },
  { y: 1, x: 5, key: "*4" },
  { y: 1, x: 6, key: "-R" },
  { y: 1, x: 7, key: "-B" },
  { y: 1, x: 8, key: "-G" },
  { y: 1, x: 9, key: "-S" },
  { y: 1, x: 10, key: "-Z" },

  { y: 2, x: 2, key: "#1" },
  { y: 2, x: 3, key: "A-" },
  { y: 2, x: 4, key: "O-" },
  { y: 2, x: 5, key: "-E" },
  { y: 2, x: 6, key: "-U" },
  { y: 2, x: 7, key: "#2" },
];
